region               = "ap-south-1"
profile              = "default"
env                  = "dev"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.3.0/24", "10.0.4.0/24"]
azs                  = ["ap-south-1a", "ap-south-1b"]
allowed_cidrs        = ["0.0.0.0/0"]
ami_id               = "ami-0abcdef1234567890"
instance_type        = "t2.micro"
key_name             = "my-key"
rds_instance_class   = "db.t3.micro"
db_name              = "mydb"
db_username          = "admin"
db_password          = "StrongPassword123"
container_definitions = file("container_definitions.json")
s3_bucket            = "my-tf-state-bucket"
dynamodb_table       = "my-tf-lock-table"
